### ISSUE TITLE
Song not found

### ISSUE THREAD

**Issue by scientistPargain** [Shubhamrawat5/Resso-playlist-downloader#3]
The whole program is working very well... But for some songs, it is saying that ==[ SONG NOT FOUND ! ]==

What should be done to download that song, or is it even possible ?
![32c09d90-5da0-4723-ba06-974bbedd85d3](https://user-images.githubusercontent.com/92857492/171000134-a5e099ed-0836-42f4-a9cf-69af6779b04d.jpg)
?

**Comment by Shubhamrawat5** [comment]
I think the song is not present in the api which I've used.  If it is giving song not found then It can't be downloaded with this tool
